export class MerchantCustomer {
    constructor(
        public id?: number,
        public serviceId?: number,
        public serviceName?: string,
        public name?: string,
        public phone?: string,
        public typeId?: number,
        public typeName?: string,
        public citizenIdNo?: string,
        public merchant?: string,
        public pob?: string,
        public dob?: string,
        public gender?: string,
        public address?: string,
        public provinceId?: number,
        public provinceName?: string,
        public postalCode?: string,
        public cityId?: number,
        public cityName?: string,
        public districtId?: number,
        public districtName?: string,
        public villageId?: number,
        public villageName?: string,
        public rw?: string,
        public rt?: string,
        public occupation?: string,
        public longitude?: number,
        public latitude?: number,
        public updatedAt?: string,
    ) { }
}