export class UpdatedDataMerchant {
    constructor(
        public id?: number,
        public mid?: number,
        public loanBankCode?: string,
        public storeName?: string,
        public expireDate?: string,
        public address?: string,
        public postalCode?: string,
        public province?: string,
        public city?: string,
        public district?: string,
        public village?: string,
        public rt?: string,
        public rw?: string,
        public loanBankAccount?: string,
        public expireDateBefore?: string,
        public storeNameBefore?: string,
        public addressBefore?: string,
        public postalCodeBefore?: string,
        public provinceBefore?: string,
        public cityBefore?: string,
        public districtBefore?: string,
        public villageBefore?: string,
        public rtBefore?: string,
        public rwBefore?: string,
        public loanBankAccountBefore?: string,
        public status?: string,
        public updatedBy?: string,
        public updatedAt?: string,
        public errCode?: string,
        public errDesc?: string,
        public merchantGroupId?: number,
        public userCategoryCode?: string,
        public partnerCode?: string,
        public partnerCustomerId?: string,
        public merchantGroupIdBefore?: number,
        public userCategoryCodeBefore?: string,
        public partnerCodeBefore?: string,
        public partnerCustomerIdBefore?: string,
        public storePhoneNumber ?: string,
        public tipeBisnis ?: string,
		public srId ?: string,
		public longitude ?: string,
		public latitude ?: string,
		public lokasiBisnis ?: string,
		public jenisLokasiBisnis ?: string,
		public categoryBisnis ?: string,
		public operationHour ?: string,
		public bestVisit ?: string,
		public userCategory ?: string,
		public patokan ?: string,
		public ownerName ?: string,
		public ownerPhoneNumber ?: string,
		public ownerAddress ?: string,
		public ownerNoId ?: string,
		public ownerTanggalLahir ?: string,
		public ownerProvinsi ?: string,
		public ownerCity ?: string,
		public ownerKecamatan ?: string,
		public ownerKelurahan ?: string,
        public ownerPostalCode ?: string,
        public storePhoneNumberBefore ?: string,
		public tipeBisnisBefore ?: string,
		public srIdBefore ?: string,
		public longitudeBefore ?: string,
		public latitudeBefore ?: string,
		public lokasiBisnisBefore ?: string,
		public jenisLokasiBisnisBefore ?: string,
		public categoryBisnisBefore ?: string,
		public operationHourBefore ?: string,
		public bestVisitBefore ?: string,
		public userCategoryBefore ?: string,
		public patokanBefore ?: string,
		public ownerNameBefore ?: string,
		public ownerPhoneNumberBefore ?: string,
		public ownerAddressBefore ?: string,
		public ownerNoIdBefore ?: string,
		public ownerTanggalLahirBefore ?: string,
		public ownerProvinsiBefore ?: string,
		public ownerCityBefore ?: string,
		public ownerKecamatanBefore ?: string,
		public ownerKelurahanBefore ?: string,
        public ownerPostalCodeBefore ?: string,
    ) { }
}
